### ISSUE TITLE
Inconsistent population of data loaded when specifying large number of tickers at once

### ISSUE THREAD

**Issue by MatassL** [dpguthrie/yahooquery#106]
I am interested in loading financials for large number of tickers at once, for example specifying all tickers for whole indexes (like DJIA, S&P500 and etc.). However, after specifying list of tickers for DJIA population (30 tickers):

_import pandas as pd
import yahooquery as yq_

_symbols = ['AAPL','AMGN','AXP','BA','CAT','CRM','CSCO','CVX','DIS','DOW','GS','HD','HON','IBM','INTC','JNJ','JPM','KO',
'MCD','MMM','MRK','MSFT','NKE','PG','TRV','UNH','V','VZ','WBA','WMT']_

_tickers = Ticker(symbols)
bs = tickers.balance_sheet(frequency="a", trailing=False)
pl = tickers.income_statement(frequency="a", trailing=False)
cf = tickers.cash_flow(frequency="a", trailing=False)_

I receive inconsistent quantity of rows returned each time (for 4 periods and 30 tickers there should be 120 rows) and for some cases large chunk is missing, for example:
_bs: 72 rows × 128 columns
pl: 116 rows × 71 columns
cf: 44 rows × 93 columns_

Question: does the logic of API in principle is not suited for these kind of bulk tickers loads or there is a matter of code improvement?

**Comment by dpguthrie** [comment]
This is most likely due to the data that Yahoo Finance is returning (i.e. the balance sheet only has the last 3 years, unless you have a premium subscription).  See this [loom video](https://www.loom.com/share/183ce9141fff40e8843819af5f0146f1) and the screenshot below of Disney.  3 years were returned because that's what is currently available.  I'm going to close this out.  Feel free to respond if this explanation doesn't suffice.

![image](https://user-images.githubusercontent.com/10198967/196002897-fae2910b-3257-45d8-b866-db5244bfa8ce.png)
