### ISSUE TITLE
 Ticker('aapl').all_modules broken

### ISSUE THREAD

**Issue by forestzhu** [dpguthrie/yahooquery#206]
**Describe the bug**
In the latest 2.3.2 and prev version 2.3.1, when running 

    Ticker('aapl').all_modules 

now returns an empty 
     {'aapl': {}} 

instead of previous all modules values.

**Comment by robinhftw** [comment]
I can confirm all_modules suddenly stopped working sometimes between July 8 and July 13. I was using 2.3.0. I updated to 2.3.2 but it still does not work, i.e., the return is empty.

**Comment by dpguthrie** [comment]
The [issue](https://github.com/dpguthrie/yahooquery/issues/203) here has some good context to what's happening.

TLDR - YF put the endpoint behind having both a cookie and crumb in the request.  Short-term fix changed the endpoint, which enabled retrieval of individual modules but broke any requests with more than one module (e.g. `all_modules`)

I'm working on a fix (this [PR](https://github.com/dpguthrie/yahooquery/pull/205) has the proposed changes).  You can install from the specific branch in the meantime if you'd like or visit the [streamlit app](https://yahooquery.streamlit.app)

**Comment by robinhftw** [comment]
Thanks! I really would like to try use that specific branch in the meantime so that I can run ticker.all_modules but are not sure how I do it. Can somebody please guide me a bit? :) In my case I have a simple python script that I run for each stock I watch during the day and that script runs ticker.all_modules (and then stores that as a json file so that I can study how float, IO etc look like for that stock at a later date). I guess I need to change the row "from yahooquery import Ticker" to something else, right?

**Comment by robinhftw** [comment]
Thanks! I tried that ("pip3 show yahooquery" now says 2.3.3), but when I run the following:

from yahooquery import Ticker
ticker = Ticker("AAPL")

I get these errors:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 836, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='query2.finance.yahoo.com', port=443): Max retries exceeded with url: /v1/test/getcrumb (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.10/site-packages/yahooquery/ticker.py", line 90, in __init__
    super(Ticker, self).__init__(**kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/yahooquery/base.py", line 938, in __init__
    self.set_crumb()
  File "/home/user/.local/lib/python3.10/site-packages/yahooquery/base.py", line 952, in set_crumb
    response = self.session.get('https://query2.finance.yahoo.com/v1/test/getcrumb')
  File "/home/user/.local/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/yahooquery/utils/__init__.py", line 139, in send
    return super(TimeoutHTTPAdapter, self).send(request, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/requests/adapters.py", line 510, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='query2.finance.yahoo.com', port=443): Max retries exceeded with url: /v1/test/getcrumb (Caused by ResponseError('too many 500 error responses'))

**Comment by dpguthrie** [comment]
Hmmm...what if you do:

```
pip install -U https://github.com/dpguthrie/yahooquery/archive/feat/set-cookie-and-crumb.zip
```

**Comment by robinhftw** [comment]
Thanks, I tried that now, i.e., using the -U in the command, and then did "from yahooquery import Ticker" followed by "ticker = Ticker("AAPL")" as before and I got the exact same error messages.

**Comment by robinhftw** [comment]
I am in northern Europe. If there is anything I can try to be able to run Ticker('stock').all_modules from my script again I will be happy to try that out.

**Comment by dpguthrie** [comment]
@robinhftw Would you mind trying this again?  I made some updates that hopefully handle errors better but also provides a fallback option using selenium (if it's installed) when cookies/crumb aren't set the first time.

**Comment by robinhftw** [comment]
Thanks! I am travelling right now, but made a quick test and now it seems to work when falling back to selenium!

**Comment by dpguthrie** [comment]
> Thanks! I am travelling right now, but made a quick test and now it seems to work when falling back to selenium!

That’s great news!  You aren’t traveling in the U.S. by chance are you?  (I’m only asking because I’ve had others outside of the U.S. say it is not working)

**Comment by robinhftw** [comment]
No, right now I´m travelling in north of Europe and did run it from a Ubuntu 22.04 system. The command Ticker('tsla').all_modules takes about 21-22 seconds to run, but I guess it is because it is falling back to selenium. Please let me know if you want me to run some debug tests or something, but for me it is nice as long as it works :)

**Comment by dpguthrie** [comment]
2.3.3 is now live in PyPi and should solve this issue. Give it a try. I imagine that there will still be some edge cases that this doesn't solve for, but was hoping to get the majority of you unblocked.  Feel free to reopen if you're still running into issues.
