### ISSUE TITLE
Cash flow data not retrieving

### ISSUE THREAD

**Issue by rdaher** [dpguthrie/yahooquery#250]
While trying to access cash flow data for many tickers, NaN values are generated for the most recent quarter.
THe issue is present whether I use ticker.all_financial_data("q"), or ticker.cash_flow("q") as shown below:

df_afdq = ticker.all_financial_data("q")

<img width="1586" alt="screenshot_996" src="https://github.com/dpguthrie/yahooquery/assets/59781123/c141e986-a768-4809-a1e4-83bedf8b6d85">

df_cf1 = ticker.cash_flow("q")
<img width="1591" alt="screenshot_995" src="https://github.com/dpguthrie/yahooquery/assets/59781123/0f962aea-6807-4c17-bbf8-c036fbeba98d">

The issue remained after upgrading from 2.3.3 to 2.3.7

**Comment by dpguthrie** [comment]
This data doesn't appear to be there yet for 9/30/23 (take a look at YF):
<img width="995" alt="image" src="https://github.com/dpguthrie/yahooquery/assets/10198967/7955031d-8dbc-442a-a550-5613f22177a2">

The reason there is a row there at all is because part of the request asks for `NetIncome`, which does have an entry for 9/30/23 and why a row is created at all.
<img width="525" alt="image" src="https://github.com/dpguthrie/yahooquery/assets/10198967/3221e335-d983-4645-870a-4790dbc2208c">

**Comment by rdaher** [comment]
Great.Yahoo used to update balance sheet, financial statements and cash flow... all at once in the recent past. Not used to seeing this delay in cash flow updates. Thank you much
