### ISSUE TITLE
Incorrect prices (by factor of 100)

### ISSUE THREAD

**Issue by CameronChandler** [dpguthrie/yahooquery#87]
**Describe the bug**
For some ASX stocks, the prices are incorrect (for some days)

**To Reproduce**
1. run `Ticker('AXE.AX').history()` and look around 2021-02-22 for one example of this.

**Expected behavior**
The prices over a few days here should be 0.80, 1.20, 1.01, 0.975, but instead are 0.80 120.00, 101.00, 0.975

**Screenshots**
![image](https://user-images.githubusercontent.com/38180257/123503547-f6dc4000-d696-11eb-806d-64dfc4ff0e4d.png)

**Comment by CameronChandler** [comment]
Obviously this effects open, low, close and high as well.

**Comment by zhenyulin** [comment]
I've also there're missing price data on certain days on Yahoo Finance as well, so as a free data source, the quality is indeed very questionable.

**Comment by dpguthrie** [comment]
Free data source = questionable data.  Not sure if this library should also be checking for anomalies within the data (happy to hear otherwise).  Seems like it's working today (probably not a consolation) :)

![image](https://user-images.githubusercontent.com/10198967/196003830-a6c22941-6245-4494-8c84-a37f47a7e8c1.png)
