### ISSUE TITLE
Error 'Invalid Crumb' when calling any module in Research Class

### ISSUE THREAD

**Issue by hkdallastx** [dpguthrie/yahooquery#93]
Error 'Invalid Crumb' when calling any module in Research Class

Very wired - Getting this error only for 'Invalid Crumb' when calling any module in Research Class and not in Premium module of Ticker Class. 

**To Reproduce**

from yahooquery import Ticker, Research, Screener
r = Research(username='myid@myid.com',password='mypd')
r.reports(report_date='Last Week')

return - {0: 'Invalid Crumb'}

**Expected behavior**
Expecting a return of data

**Screenshots**
![image](https://user-images.githubusercontent.com/89328706/130343736-618df3c7-d9eb-4b21-85cd-99cf0d16b091.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser chrome 92
 - Version 2.2.15

**Comment by dpguthrie** [comment]
This is most likely due to YF restricting part of their app now via a crumb.  I've tried to work around it by grabbing the crumb when you login, which I think is something they've also changed from the last time I've looked.

I'm closing this as not something I'll fix but would be more than happy to accept a PR.

**Comment by hkdltx** [comment]
Hi, I tried what you suggested and wasn't able to grab get the crumb to work.  Something I am missing. Can you please accept this as a PR. I will continue to try to get it to work and let u know if I get any success.
